version: '3'

networks:
    app-tier:
        driver: bridge

volumes:
    postgres_data: {}
    pgadmin_data: {}

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'server'
        stdin_open: true
        tty: true
        env_file:
            - .env
        networks:
            - app-tier
        depends_on:
            - postgres
        volumes:
            - .:/api
        working_dir: /api
        ports:
            - 3000:3000

    postgres:
        image: postgres:17
        container_name: 'postgres'
        env_file:
            - .env
        networks:
            - app-tier
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
